#!/usr/bin/env ruby
# frozen_string_literal: true

# Block showcase - generates HTML files to visually test blocks (without Rails Engine)

# Load individual components
require_relative '../lib/rails/page/builder/version'
require_relative '../lib/rails/page/builder/configuration'
require_relative '../lib/rails/page/builder/block_contents'
require_relative '../lib/rails/page/builder/block_library'

# Set up basic configuration
module Rails
  module Page
    module Builder
      @configuration = nil
      
      class << self
        def configuration
          @configuration ||= Configuration.new
        end
        
        def configure
          yield(configuration)
        end
      end
    end
  end
end

puts "🎨 Generating Block Showcase..."

# Create examples directory if it doesn't exist
Dir.mkdir('examples') unless Dir.exist?('examples')
Dir.mkdir('examples/output') unless Dir.exist?('examples/output')

# Configure
Rails::Page::Builder.configure do |config|
  config.supported_languages = [:en, :fa, :ar, :he]
end

def generate_showcase_html(language = :en)
  is_rtl = [:fa, :ar, :he].include?(language)
  
  html = <<~HTML
    <!DOCTYPE html>
    <html lang="#{language}" dir="#{is_rtl ? 'rtl' : 'ltr'}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Rails Page Builder - Block Showcase (#{language.upcase})</title>
        <style>
            body {
                font-family: 'Arial', sans-serif;
                margin: 0;
                padding: 20px;
                background: #f5f5f5;
                direction: #{is_rtl ? 'rtl' : 'ltr'};
            }
            
            .showcase-header {
                text-align: center;
                margin-bottom: 40px;
                padding: 20px;
                background: white;
                border-radius: 12px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            
            .block-section {
                margin-bottom: 40px;
                background: white;
                border-radius: 12px;
                padding: 20px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            
            .block-title {
                font-size: 1.5rem;
                font-weight: 600;
                margin-bottom: 20px;
                color: #495057;
                border-bottom: 2px solid #007bff;
                padding-bottom: 10px;
            }
            
            .block-description {
                color: #6c757d;
                margin-bottom: 20px;
                font-style: italic;
            }
            
            .block-item {
                margin-bottom: 30px;
                border: 1px solid #e9ecef;
                border-radius: 8px;
                overflow: hidden;
            }
            
            .block-header {
                background: #f8f9fa;
                padding: 15px;
                border-bottom: 1px solid #e9ecef;
            }
            
            .block-content {
                padding: 20px;
            }
        </style>
    </head>
    <body>
        <div class="showcase-header">
            <h1>🚀 Rails Page Builder Showcase</h1>
            <p>Language: #{language.upcase} #{is_rtl ? '(RTL)' : '(LTR)'}</p>
            <p>Showcasing all available blocks and components</p>
        </div>
  HTML
  
  # Get all block categories
  all_blocks = Rails::Page::Builder::BlockLibrary.all_blocks(language)
  
  # Group blocks by category
  blocks_by_category = all_blocks.group_by { |block| block[:category] }
  
  blocks_by_category.each do |category, blocks|
    html += <<~HTML
      <div class="block-section">
          <div class="block-title">#{category}</div>
          <div class="block-description">Blocks in the #{category} category (#{blocks.count} blocks)</div>
    HTML
    
    blocks.each do |block|
      html += <<~HTML
        <div class="block-item">
            <div class="block-header">
                <strong>#{block[:icon]} #{block[:label]}</strong>
                <span style="color: #6c757d; margin-#{is_rtl ? 'right' : 'left'}: 10px;">(#{block[:id]})</span>
            </div>
            <div class="block-content">
                #{block[:content]}
            </div>
        </div>
      HTML
    end
    
    html += "</div>"
  end
  
  html += <<~HTML
        <div class="showcase-header">
            <p>Generated by Rails Page Builder</p>
            <p>Total blocks: #{all_blocks.count} | Categories: #{blocks_by_category.keys.count}</p>
            <p>Language: #{language.upcase} (#{is_rtl ? 'Right-to-Left' : 'Left-to-Right'})</p>
        </div>
    </body>
    </html>
  HTML
  
  html
end

# Generate showcases for each language
[:en, :fa, :ar, :he].each do |language|
  puts "Generating showcase for #{language.upcase}..."
  
  begin
    html_content = generate_showcase_html(language)
    filename = "examples/output/block_showcase_#{language}.html"
    
    File.write(filename, html_content)
    puts "✅ Generated: #{filename} (#{html_content.length} chars)"
    
  rescue => e
    puts "❌ Error generating #{language}: #{e.message}"
    puts e.backtrace.first(3)
  end
end

puts "\n🎉 Block showcases generated successfully!"
puts "📁 Files created:"
puts "   - examples/output/block_showcase_en.html (English)"
puts "   - examples/output/block_showcase_fa.html (Persian/Farsi)"  
puts "   - examples/output/block_showcase_ar.html (Arabic)"
puts "   - examples/output/block_showcase_he.html (Hebrew)"
puts "\n🌐 Open these HTML files in your browser to see the visual results!"
puts "💡 Tip: Check the RTL languages to see right-to-left text direction in action."